### PR TITLE
implemented easter holiday with anonymous gregorian algorithm

### PR DESCRIPTION
**Pull request by demus**
https://en.wikipedia.org/wiki/Computus#Anonymous_Gregorian_algorithm

### CODE REVIEW

**Comment by water42** [comment]
I was also thinking about adding Good Friday as the observed date for Easter, any thoughts on this?

**Comment by elidoran** [comment]
Thank you for the PR. 

As for Good Friday being an "observed" day for Easter,  it seems like Good Friday and Easter Sunday are separate because they play a different part in that whole time frame starting with Palm Sunday. What do you think about adding Good Friday on its own?

I used the "observed" ones for holidays which move around and we "observe" them on a second day for a day off during the week. It's the same holiday though.

I could be wrong. I admit I'm not as familiar with what everyone does for the religious holidays. I  included Christmas because it's a federal bank holiday.

Do some groups take the day off for Good Friday? I thought it represented the day of the crucifixion and Easter Sunday is for the resurrection, so, they're separate. Am I wrong?

I was originally going to add in Easter but put it off because I thought it might be better to group a bunch of religious holidays and I know there are many more of them. Basically, I marked it "research more" and moved on. :)

**Comment by water42** [comment]
No problem, thanks for the library!

In my state Good Friday is a public holiday, along with [several other states ](https://en.wikipedia.org/wiki/Public_holidays_in_the_United_States#Legal_holidays_by_states_and_political_divisions_of_the_United_States). My understanding is that Good Friday always occurs two days before Easter Sunday, which means that it depends on the Easter calculation. It doesn't quite fit in the observed list though, and it is easy enough to subtract two days from the Easter date.

**Comment by elidoran** [comment]
This is a great example why I started with a library for everyone to use to throw in their own holidays. There is so much variance based on geography and beliefs. I prefer to avoid storing a ton of info which is only used by some. There is one holidays module in NPM which has a ton of info. It has thousands and thousands of lines of holidays by region all over the world. That's great, except, when I want only the US federal bank holidays, I get all the holidays in the world instead. I'd like to avoid that scenario.

I made this module because I needed the US bank holidays for an app I made at work.

It's true we can easily subtract two days from Easter, but, if we want `holidays.isHoliday(goodFridayDate)` to return true then it'd need to be in there. Same with `getHoliday()`.

I like to accept options objects to the builder function exported by the module. I didn't do that this time, but, I should have. What do you think about accepting an options object for this module which allows disabling some holidays, or, specifying which holidays to enable?

Right now I have the holidays specified in groups in two functions. I could instead separate them all into their own generator functions and only add them to the holidays instance if enabled, or, not disabled. 

Then, it'd be possible to put a whole bunch of generators into this module while still allowing users of the module to choose which ones are used.  For example:

``` coffeescript
# this would use all the holidays
holidays = require('@date/holidays-us')()

# this wouldn't add the holidays listed in the disable array
holidays = require('@date/holidays-us')
  disable: [
    'Good Friday'
  ]

# this would be the opposite accepting an enable list:
holidays = require('@date/holidays-us')
  enable: [
    'New Year\'s Eve', 'Christmas' # you get the idea :)
  ]
```

It's possible to store regional data in the holiday info and then allow selecting based on that. For example, in an info do a state with true, like `GA:true`, and then they can make a call using that like `holidays.isHoliday date, {GA:true}`. I'd rather not store a bunch of regional data tho, and, that doesn't seem super user friendly for the devs either.

Hmm.

**Comment by elidoran** [comment]
Remembered to merge your changes into my local changes and publish a new version, 0.3.0, with all of it.

**Comment by elidoran** [comment]
What do you think about this design: place functions like easter() in their own module: `@date/holiday-easter`. Along with the holiday generator function to add to a `holidays` instance. Then, we'd be able to publish the code for as many holiday calculations as everyone wants and they could grab them and add them to their `holidays` instance in any combination they want. I could provide the default "holiday info" (name, bank:true, public:true, whatever...) which they could override.

Then, they'd do something like:

``` coffeescript
myholidays = require('holidays')()

easter = require 'holidays-easter'

# can use directly...
nextEaster = easter 2017

# can stick on the holidays instance like I did in the US one
myholidays.easter = easter

# or add its holiday generator to a holidays instance
# the secondary function is a sub-property of the date calculator function
myholidays.add easter.holiday
```

The generator function provides the "holiday info", so, to allow that to be overridden I'd have to accept info at that `add()` which may require changing how it is provided anywhere, we'll see what I come up with.

I still think some aggregating modules with a bunch of holidays are helpful, such as `@date/holidays-us`, I just want to avoid them getting out of control. :)   They'd simply do like the above to pre-populate the `holidays` instance with holidays.

**Pull request merged**
